version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - ~/data/mongodb:/data/db
    networks:
      - internal
      - local

  redis:
    image: redis
    networks:
      - internal
      - local

  app:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - mongo
      - redis
    networks:
      - internal
      - local

networks:
  internal:
    driver: bridge
  local:
    external: true