version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - ~/data/mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - internal

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - internal

  app:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - mongo
      - redis
    networks:
      - internal

networks:
  internal:
    driver: bridge